### ISSUE TITLE
2G_ALE and FAX extensions that are present on the KiWi are missing on the Flydog fork

### ISSUE THREAD

**Issue by G8JNJ** [flydog-sdr/FlyDog_SDR_GPS#84]
2G_ALE and FAX extensions that are present on the KiWi are missing on the v1.573 Flydog fork

**Comment by bclswl0827** [comment]
> KiWi 上存在的 2G_ALE 和 FAX 扩展在 v1.573 Flydog 分支上缺失

Hello, ALE and FAX extensions were removed in FlyDog SDR.

**Comment by G8JNJ** [comment]
我知道他们失踪了。 这样做有什么原因吗？

I'm aware they are missing.

Is there a reason why this has been done ?

**Comment by bclswl0827** [comment]
These extensions has come back in the latest release
