### ISSUE TITLE
Periodic sync updates?

### ISSUE THREAD

**Issue by azwirko** [flydog-sdr/FlyDog_SDR_GPS#95]
Hi 

Is it possible to sync the FlyDog_SDR code base to the main KiwiSDR branch at least quarterly (4 times a year?)  It been 3+ months since the last synchronization update.

Thanks for your continued support.

andyz - K1RA

**Comment by G8JNJ** [comment]
Hi,

There have been significant changes and upgrades to the KiWi since the last release of Flydog.

I would also appreciate more frequent updates. 

Thanks,

Martin

**Comment by bclswl0827** [comment]
Hi, the code has been updated to v1.624 (Sep. 6), and this issue will be closed.
You can reopen it anytime if you have further questions.
